### ISSUE TITLE
Start Page

### ISSUE THREAD

**Issue by frankwiles** [simplworld/simpl-blackjack-ui#9]
- [ ] Game explanation / copy from @dinaluciano 
- [ ] Start button

**Comment by dinaluciano** [comment]
See this document for changes.  (I didn't include the login page, but let me know...I can.  ) 

The instructions for Blackjack interstitial are the #simpl_blackjack  channel here:  https://wharton.slack.com/archives/GN62Q4VB2/p1570205984008200
